name: C/C++ CI

on:
  push:
    branches: [ master, cicd ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependancies
      run: sudo apt-get -y install build-essential libsdl1.2debian libsdl1.2debian libsdl1.2-dev libsdl-image1.2 libsdl-image1.2-dev libopenal1 libopenal-dev libvorbis-dev libcurl4 libcurl4-openssl-dev
    - uses: actions/checkout@v2
    - name: make
      run: make server_install
      working-directory: source/src
    - uses: actions/upload-artifact@main
      with:
        name: bin
        path: bin/*

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: fruity
    
    steps:
    - uses: actions/download-artifact@main
      with: 
        name: bin
        path: bin/
    - name: copy file via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "bin"
        target: "~/github_upload/commit_${{github.sha}}/"
